import { useState } from 'react';
import { CreditCard, Plus, Pencil, CheckCircle2 } from 'lucide-react';
import { useWallet } from '../components/WalletContext';
import { cardUsage, dateBR, invoiceStatus, money, monthLabel } from '../domain/finance';
import { Button, Empty, StatusBadge } from '../components/ui';
import { CatalogEditor, TransactionEditor } from '../components/Editors';
import { TransactionList } from '../components/TransactionList';
import { walletService } from '../data/wallet-service';
import type { Card } from '../domain/types';
export function Cards() {
  const { state, ctx, scope, month, run } = useWallet(); const [selection, setSelection] = useState(''), [cycle, setCycle] = useState(''), [person, setPerson] = useState(''), [editor, setEditor] = useState<Card | 'new' | null>(null), [purchase, setPurchase] = useState(false);
  const cards = state.cards.filter(c => c.scope === scope), card = cards.find(c => c.id === selection) ?? cards[0];
  const invoices = state.invoices.filter(i => i.cardId === card?.id).sort((a, b) => a.cycleMonth.localeCompare(b.cycleMonth));
  const invoice = invoices.find(i => i.cycleMonth === (cycle || month)) ?? invoices.find(i => i.cycleMonth >= month) ?? invoices[invoices.length - 1];
  const transactions = state.transactions.filter(t => t.cardId === card?.id), purchases = transactions.filter(t => t.invoiceId === invoice?.id && (!person || t.personId === person));
  const usage = card ? cardUsage(card, transactions, invoices) : null, total = purchases.filter(t => t.status !== 'cancelled').reduce((sum, t) => sum + t.amount, 0);
  return <div><div className="section-toolbar"><p className="muted">Acompanhe seus limites e faturas em um só lugar.</p><Button variant="secondary" onClick={() => setEditor('new')}><Plus size={17} />Adicionar cartão</Button></div>{cards.length ? <><div className="card-selector">{cards.map((c, index) => <button className={`bank-card ${c.id === card?.id ? 'active' : ''} card-color-${index % 3}`} key={c.id} onClick={() => { setSelection(c.id); setCycle(''); }}><div><span>{c.bank}</span><CreditCard size={26} /></div><strong>{c.name}</strong><p>•••• &nbsp; •••• &nbsp; •••• &nbsp; {c.last4Digits}</p><footer><span>{state.people.find(p => p.id === c.ownerPersonId)?.name ?? 'Titular'}{!c.active && ' · Inativo'}</span><b>{c.brand}</b></footer></button>)}</div>{card && usage && <div className="card-detail"><section className="panel"><div className="panel-heading"><h2>{card.name}</h2><Button variant="ghost" onClick={() => setEditor(card)}><Pencil size={15} />Editar</Button></div><div className="limit-summary"><div><small>Limite disponível</small><strong>{money(usage.available)}</strong></div><div><small>Limite utilizado</small><strong>{money(usage.used)}</strong></div><div><small>Limite total</small><strong>{money(card.totalLimit)}</strong></div></div><div className="limit-progress"><div className="progress-track"><div className={usage.percent > 100 ? 'over' : ''} style={{ width: `${Math.min(usage.percent, 100)}%` }} /></div><small>{Math.round(usage.percent)}% comprometido · Inclui parcelas futuras não quitadas</small></div><div className="card-dates"><span>Fecha dia <strong>{card.closingDay}</strong></span><span>Vence dia <strong>{card.dueDay}</strong></span>{card.active && <Button variant="secondary" onClick={() => setPurchase(true)}><Plus size={16} />Registrar compra</Button>}</div></section>
  <section className="panel"><div className="panel-heading"><h2>Fatura</h2>{invoice && <select aria-label="Selecionar fatura" value={invoice.cycleMonth} onChange={e => setCycle(e.target.value)}>{invoices.map(i => <option key={i.id} value={i.cycleMonth}>{monthLabel(i.cycleMonth)} · fechamento</option>)}</select>}</div>{invoice ? <><div className="invoice-overview"><div><small>{person ? 'Total para a pessoa selecionada' : 'Total da fatura'}</small><strong>{money(total)}</strong><p>Vencimento em {dateBR(invoice.dueDate)} · Fecha {dateBR(invoice.closingDate)}</p></div><StatusBadge status={invoiceStatus(invoice)} /><Button variant="secondary" onClick={() => run(() => walletService.setInvoicePaid(ctx, invoice.id, !invoice.paidAt), invoice.paidAt ? 'Fatura reaberta.' : 'Fatura marcada como paga. O pagamento não cria outra despesa.')}><CheckCircle2 size={16} />{invoice.paidAt ? 'Reabrir fatura' : 'Marcar como paga'}</Button></div><div className="invoice-filter"><select aria-label="Filtrar fatura por pessoa" value={person} onChange={e => setPerson(e.target.value)}><option value="">Todas as pessoas</option>{state.people.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></div><TransactionList items={purchases.map(t => ({ ...t, rowType: 'transaction' }))} /><div className="future-invoices"><h3>Próximas faturas</h3>{invoices.filter(i => i.cycleMonth > invoice.cycleMonth).slice(0, 6).map(i => <button key={i.id} onClick={() => setCycle(i.cycleMonth)}><span>{monthLabel(i.cycleMonth)}</span><strong>{money(transactions.filter(t => t.invoiceId === i.id && t.status !== 'cancelled').reduce((sum, t) => sum + t.amount, 0))}</strong><small>Vence {dateBR(i.dueDate)}</small></button>)}{!invoices.some(i => i.cycleMonth > invoice.cycleMonth) && <p className="muted">Nenhuma fatura futura registrada.</p>}</div></> : <Empty title="Seu cartão está pronto" description="Registre uma compra para criar a primeira fatura." action={<Button onClick={() => setPurchase(true)}>Registrar compra</Button>} />}</section></div>}</> : <section className="panel"><Empty title="Seus cartões, sem surpresas" description="Adicione um cartão para organizar compras e acompanhar as próximas faturas." action={<Button onClick={() => setEditor('new')}><Plus size={17} />Adicionar primeiro cartão</Button>} /></section>}{editor && <CatalogEditor kind="cards" existing={editor === 'new' ? undefined : editor} onClose={() => setEditor(null)} />}{purchase && <TransactionEditor initialCard={card?.id} onClose={() => setPurchase(false)} />}</div>;
}
