import { useState } from 'react';
import { CreditCard, Plus, Pencil, CheckCircle2 } from 'lucide-react';
import { useWallet } from '../components/WalletContext';
import { accountBalance, cardUsage, dateBR, invoiceStatus, money, monthLabel } from '../domain/finance';
import { Button, Empty, StatusBadge } from '../components/ui';
import { CatalogEditor, TransactionEditor } from '../components/Editors';
import { TransactionList } from '../components/TransactionList';
import { walletService } from '../data/wallet-service';
import type { Card } from '../domain/types';

export function Cards() {
  const { state, ctx, scope, month, run } = useWallet();
  const [selection, setSelection] = useState(''), [cycle, setCycle] = useState(''), [person, setPerson] = useState('');
  const [editor, setEditor] = useState<Card | 'new' | null>(null), [purchase, setPurchase] = useState(false);
  const cards = state.cards.filter(card => card.scope === scope);
  const card = cards.find(current => current.id === selection) ?? cards[0];
  const invoices = state.invoices.filter(invoice => invoice.cardId === card?.id).sort((a, b) => a.cycleMonth.localeCompare(b.cycleMonth));
  const invoice = invoices.find(current => current.cycleMonth === (cycle || month)) ?? invoices.find(current => current.cycleMonth >= month) ?? invoices[invoices.length - 1];
  const transactions = state.transactions.filter(transaction => transaction.cardId === card?.id);
  const purchases = transactions.filter(transaction => transaction.invoiceId === invoice?.id && (!person || transaction.personId === person));
  const debitPurchases = transactions.filter(transaction => !person || transaction.personId === person);
  const usage = card?.cardType === 'credit' ? cardUsage(card, transactions, invoices) : null;
  const total = purchases.filter(transaction => transaction.status !== 'cancelled').reduce((sum, transaction) => sum + transaction.amount, 0);
  const debitAccount = card?.cardType === 'debit' ? state.accounts.find(account => account.id === card.accountId) : undefined;

  return <div>
    <div className="section-toolbar"><p className="muted">Acompanhe cartões de crédito e débito em um só lugar.</p><Button variant="secondary" onClick={() => setEditor('new')}><Plus size={17} />Adicionar cartão</Button></div>
    {cards.length ? <>
      <div className="card-selector">{cards.map((current, index) => <button className={`bank-card ${current.id === card?.id ? 'active' : ''} card-color-${index % 3}`} key={current.id} onClick={() => { setSelection(current.id); setCycle(''); }}><div><span>{current.bank}</span><CreditCard size={26} /></div><strong>{current.name}</strong><p>•••• &nbsp; •••• &nbsp; •••• &nbsp; {current.last4Digits}</p><footer><span>{state.people.find(owner => owner.id === current.ownerPersonId)?.name ?? 'Titular'}{!current.active && ' · Inativo'}</span><b>{current.cardType === 'debit' ? 'Débito' : `Crédito · ${current.brand}`}</b></footer></button>)}</div>
      {card?.cardType === 'debit' ? <div className="card-detail">
        <section className="panel"><div className="panel-heading"><h2>{card.name}</h2><Button variant="ghost" onClick={() => setEditor(card)}><Pencil size={15} />Editar</Button></div><div className="limit-summary"><div><small>Saldo da conta vinculada</small><strong>{money(debitAccount ? accountBalance(debitAccount.id, state.transactions, state.transfers, state.cards) : 0)}</strong></div><div><small>Conta debitada</small><strong>{debitAccount?.name ?? 'Indisponível'}</strong></div></div><div className="card-dates"><span>Cartão de <strong>débito</strong></span>{card.active && <Button variant="secondary" onClick={() => setPurchase(true)}><Plus size={16} />Registrar compra</Button>}</div></section>
        <section className="panel"><div className="panel-heading"><h2>Compras no débito</h2><select aria-label="Filtrar compras por pessoa" value={person} onChange={event => setPerson(event.target.value)}><option value="">Todas as pessoas</option>{state.people.map(current => <option key={current.id} value={current.id}>{current.name}</option>)}</select></div>{debitPurchases.length ? <TransactionList items={debitPurchases.map(transaction => ({ ...transaction, rowType: 'transaction' }))} /> : <Empty title="Nenhuma compra no débito" description="Registre uma compra para descontá-la do saldo da conta vinculada." action={<Button onClick={() => setPurchase(true)}>Registrar compra</Button>} />}</section>
      </div> : card && usage && <div className="card-detail">
        <section className="panel"><div className="panel-heading"><h2>{card.name}</h2><Button variant="ghost" onClick={() => setEditor(card)}><Pencil size={15} />Editar</Button></div><div className="limit-summary"><div><small>Limite disponível</small><strong>{money(usage.available)}</strong></div><div><small>Limite utilizado</small><strong>{money(usage.used)}</strong></div><div><small>Limite total</small><strong>{money(card.totalLimit)}</strong></div></div><div className="limit-progress"><div className="progress-track"><div className={usage.percent > 100 ? 'over' : ''} style={{ width: `${Math.min(usage.percent, 100)}%` }} /></div><small>{Math.round(usage.percent)}% comprometido · Inclui parcelas futuras não quitadas</small></div><div className="card-dates"><span>Fecha dia <strong>{card.closingDay}</strong></span><span>Vence dia <strong>{card.dueDay}</strong></span>{card.active && <Button variant="secondary" onClick={() => setPurchase(true)}><Plus size={16} />Registrar compra</Button>}</div></section>
        <section className="panel"><div className="panel-heading"><h2>Fatura</h2>{invoice && <select aria-label="Selecionar fatura" value={invoice.cycleMonth} onChange={event => setCycle(event.target.value)}>{invoices.map(current => <option key={current.id} value={current.cycleMonth}>{monthLabel(current.cycleMonth)} · fechamento</option>)}</select>}</div>{invoice ? <><div className="invoice-overview"><div><small>{person ? 'Total para a pessoa selecionada' : 'Total da fatura'}</small><strong>{money(total)}</strong><p>Vencimento em {dateBR(invoice.dueDate)} · Fecha {dateBR(invoice.closingDate)}</p></div><StatusBadge status={invoiceStatus(invoice)} /><Button variant="secondary" onClick={() => run(() => walletService.setInvoicePaid(ctx, invoice.id, !invoice.paidAt), invoice.paidAt ? 'Fatura reaberta.' : 'Fatura marcada como paga. O pagamento não cria outra despesa.')}><CheckCircle2 size={16} />{invoice.paidAt ? 'Reabrir fatura' : 'Marcar como paga'}</Button></div><div className="invoice-filter"><select aria-label="Filtrar fatura por pessoa" value={person} onChange={event => setPerson(event.target.value)}><option value="">Todas as pessoas</option>{state.people.map(current => <option key={current.id} value={current.id}>{current.name}</option>)}</select></div><TransactionList items={purchases.map(transaction => ({ ...transaction, rowType: 'transaction' }))} /><div className="future-invoices"><h3>Próximas faturas</h3>{invoices.filter(current => current.cycleMonth > invoice.cycleMonth).slice(0, 6).map(current => <button key={current.id} onClick={() => setCycle(current.cycleMonth)}><span>{monthLabel(current.cycleMonth)}</span><strong>{money(transactions.filter(transaction => transaction.invoiceId === current.id && transaction.status !== 'cancelled').reduce((sum, transaction) => sum + transaction.amount, 0))}</strong><small>Vence {dateBR(current.dueDate)}</small></button>)}{!invoices.some(current => current.cycleMonth > invoice.cycleMonth) && <p className="muted">Nenhuma fatura futura registrada.</p>}</div></> : <Empty title="Seu cartão está pronto" description="Registre uma compra para criar a primeira fatura." action={<Button onClick={() => setPurchase(true)}>Registrar compra</Button>} />}</section>
      </div>}
    </> : <section className="panel"><Empty title="Seus cartões, sem surpresas" description="Adicione um cartão para organizar compras e acompanhar faturas ou débitos em conta." action={<Button onClick={() => setEditor('new')}><Plus size={17} />Adicionar primeiro cartão</Button>} /></section>}
    {editor && <CatalogEditor kind="cards" existing={editor === 'new' ? undefined : editor} onClose={() => setEditor(null)} />}
    {purchase && <TransactionEditor initialCard={card?.id} onClose={() => setPurchase(false)} />}
  </div>;
}
