import { ArrowDownRight, ArrowUpRight, ChevronDown, ChevronRight, Plus, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { accountBalance, budgetUsage, cardUsage, dateBR, financialDate, money, monthlyTotals, normalize, parseDate } from '../domain/finance';
import type { Budget, Transaction } from '../domain/types';
import { useWallet } from '../components/WalletContext';
import { Button, CategoryIcon, Empty } from '../components/ui';
import { TransactionList } from '../components/TransactionList';
export function BudgetBars({ budgets, transactions }: { budgets: Budget[]; transactions: Transaction[] }) {
  return <div className="budget-bars">{budgets.map(b => { const usage = budgetUsage(b, transactions); return <div className="budget-item" key={b.id}><div><strong>{b.name}</strong><span>{money(usage.used)} <small>/ {money(b.limitAmount)}</small></span></div><div className="progress-line"><div className="progress-track" role="progressbar" aria-label={`Orçamento ${b.name}`} aria-valuenow={usage.percent} aria-valuemin={0} aria-valuemax={100}><div className={usage.percent >= 100 ? 'over' : usage.percent >= 80 ? 'warning' : ''} style={{ width: `${Math.min(usage.percent, 100)}%` }} /></div><span>{usage.percent}%</span></div></div>; })}</div>;
}
function MovementChart({ transactions, month }: { transactions: Transaction[]; month: string }) {
  const start = parseDate(`${month}-01`), days = new Date(start.getFullYear(), start.getMonth() + 1, 0).getDate();
  const daily = Array.from({ length: days }, (_, day) => ({ income: 0, expense: 0, day: day + 1 }));
  for (const tx of transactions) if (tx.status === 'confirmed' && financialDate(tx).startsWith(month)) daily[Number(financialDate(tx).slice(8, 10)) - 1][tx.type] += tx.amount;
  const max = Math.max(10000, ...daily.flatMap(d => [d.income, d.expense]));
  const ceiling = Math.ceil(max / 10000) * 10000, step = 630 / days;
  const activeDays = daily.filter(day => day.income || day.expense);
  return <><svg className="movement-chart" viewBox="0 0 710 246" role="img" aria-label={`Receitas e despesas confirmadas por dia de ${month}. Receita ${money(daily.reduce((s, d) => s + d.income, 0))}; despesas ${money(daily.reduce((s, d) => s + d.expense, 0))}.`}>
    <defs><pattern id="expense-pattern" width="5" height="5" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="5" height="5" fill="#8BC8A7" /><line x1="0" x2="0" y1="0" y2="5" stroke="#3C8060" strokeWidth="2" /></pattern></defs>
    {[0, 1, 2, 3, 4].map(i => <g key={i}><line x1="62" x2="698" y1={18 + i * 46} y2={18 + i * 46} className="chart-grid" /><text x="51" y={22 + i * 46} textAnchor="end">{new Intl.NumberFormat('pt-BR', { notation: 'compact' }).format(ceiling * (4 - i) / 400)}</text></g>)}
    {daily.map((d, i) => <g key={d.day} tabIndex={d.income || d.expense ? 0 : undefined} role={d.income || d.expense ? 'group' : undefined} aria-label={d.income || d.expense ? `Dia ${d.day}: receitas ${money(d.income)}; despesas ${money(d.expense)}` : undefined}><rect x={65 + i * step} y={202 - d.income / ceiling * 184} width={Math.max(3, step * .28)} height={d.income / ceiling * 184} fill="#008847" rx="1"><title>{d.day}: receitas {money(d.income)}</title></rect><rect x={66 + i * step + step * .32} y={202 - d.expense / ceiling * 184} width={Math.max(3, step * .28)} height={d.expense / ceiling * 184} fill="url(#expense-pattern)" rx="1"><title>{d.day}: despesas {money(d.expense)}</title></rect>{[1, 5, 10, 15, 20, 25, days].includes(d.day) && <text x={67 + i * step} y="230" textAnchor="middle">{String(d.day).padStart(2, '0')}</text>}</g>)}
  </svg><table className="visually-hidden"><caption>Movimentação confirmada por dia</caption><thead><tr><th>Dia</th><th>Receitas</th><th>Despesas</th></tr></thead><tbody>{activeDays.map(day => <tr key={day.day}><td>{day.day}</td><td>{money(day.income)}</td><td>{money(day.expense)}</td></tr>)}</tbody></table></>;
}
export function Dashboard({ onAdd }: { onAdd: () => void }) {
  const { state, scope, month } = useWallet(), [query, setQuery] = useState(''), [showDetails, setShowDetails] = useState(false);
  const categoryById = useMemo(() => new Map(state.categories.map(category => [category.id, category])), [state.categories]);
  const transactions = useMemo(() => state.transactions.filter(transaction => transaction.scope === scope), [state.transactions, scope]);
  const totals = useMemo(() => monthlyTotals(transactions, month), [transactions, month]);
  const confirmed = useMemo(() => transactions.filter(transaction => transaction.type === 'expense' && transaction.status === 'confirmed' && financialDate(transaction).startsWith(month)), [transactions, month]);
  const categories = useMemo(() => {
    const amountByCategory = new Map<string, number>();
    for (const transaction of confirmed) amountByCategory.set(transaction.categoryId, (amountByCategory.get(transaction.categoryId) ?? 0) + transaction.amount);
    return state.categories.map(category => ({ ...category, amount: amountByCategory.get(category.id) ?? 0 })).filter(category => category.amount > 0).sort((a, b) => b.amount - a.amount);
  }, [confirmed, state.categories]);
  const topCategories = categories.slice(0, 3); const remainder = categories.slice(3).reduce((s, c) => s + c.amount, 0);
  const chartCategories = [...topCategories, ...(remainder ? [{ id: 'other', name: 'Outros', amount: remainder }] : [])];
  const colors = ['#008847', '#246B50', '#4D7F86', '#A9681D'];
  let offset = 0;
  const segments = chartCategories.map((c, i) => { const from = offset; offset += c.amount / Math.max(1, totals.expense) * 100; return `${colors[i]} ${from}% ${offset}%`; });
  const recent = useMemo(() => transactions.filter(transaction => financialDate(transaction).startsWith(month) && normalize(transaction.name + ' ' + (categoryById.get(transaction.categoryId)?.name ?? '')).includes(normalize(query))).sort((a, b) => financialDate(b).localeCompare(financialDate(a)) || b.createdAt.localeCompare(a.createdAt)).slice(0, 6), [transactions, month, query, categoryById]);
  const budgets = useMemo(() => state.budgets.filter(budget => budget.scope === scope && budget.month === month && budget.active), [state.budgets, scope, month]);
  const upcoming = useMemo(() => transactions.filter(transaction => (transaction.status === 'forecast' || transaction.status === 'pending') && financialDate(transaction).startsWith(month)).sort((a, b) => financialDate(a).localeCompare(financialDate(b))).slice(0, 4), [transactions, month]);
  const largestExpenses = useMemo(() => confirmed.slice().sort((a, b) => b.amount - a.amount).slice(0, 4), [confirmed]);
  return <div className="dashboard"><div className="metrics"><article className="metric balance"><div><span>Saldo do mês</span><strong>{money(totals.balance)}</strong><small>Receitas menos despesas confirmadas</small></div><span className="metric-icon"><ArrowUpRight size={22} /></span></article><article className="metric"><div><span>Receitas</span><strong>{money(totals.income)}</strong><small>Total de entradas confirmadas</small></div><span className="metric-icon positive"><ArrowUpRight size={22} /></span></article><article className="metric"><div><span>Despesas</span><strong>{money(totals.expense)}</strong><small>Total de saídas confirmadas</small></div><span className="metric-icon negative"><ArrowDownRight size={22} /></span></article></div>
  <div className="dashboard-charts"><section className="panel"><div className="panel-heading"><h2>Movimentação do mês</h2><div className="chart-legend"><span><i />Receitas</span><span><i />Despesas</span></div></div><MovementChart transactions={transactions} month={month} /></section><section className="panel"><div className="panel-heading"><h2>Onde você gastou</h2></div>{totals.expense ? <div className="category-chart"><div className="donut" style={{ background: `conic-gradient(${segments.join(',')})` }} role="img" aria-label={chartCategories.map(c => `${c.name}: ${money(c.amount)}`).join('; ')}><div><strong>{money(totals.expense)}</strong><small>Total</small></div></div><div className="category-legend">{chartCategories.map((c, i) => <div key={c.id}><i style={{ background: colors[i] }} /><span><strong>{c.name}</strong><small>{money(c.amount)}</small></span><small>{Math.round(c.amount / totals.expense * 100)}%</small></div>)}</div></div> : <Empty title="Cada gasto conta uma história" description="Suas despesas confirmadas aparecerão por categoria." />}</section></div>
  <div className="dashboard-bottom"><section className="panel recent-panel"><div className="panel-heading"><h2>Últimos lançamentos</h2><Link to="/app/historico" className="text-button">Ver todos <ChevronRight size={16} /></Link></div><div className="inline-search"><Search size={16} /><input aria-label="Buscar lançamentos no resumo" placeholder="Buscar no mês…" value={query} onChange={e => setQuery(e.target.value)} /></div>{transactions.length ? <TransactionList items={recent.map(t => ({ ...t, rowType: 'transaction' }))} compact /> : <Empty title="Seu primeiro passo começa aqui" description="Registre uma receita ou despesa para acompanhar o seu mês." action={<Button onClick={onAdd}><Plus size={17} />Adicionar lançamento</Button>} />}</section><section className="panel"><div className="panel-heading"><h2>Orçamentos</h2><Link to="/app/ajustes/orcamentos" aria-label="Gerenciar orçamentos" className="icon-button"><ChevronRight size={18} /></Link></div>{budgets.length ? <BudgetBars budgets={budgets.slice(0, 4)} transactions={transactions} /> : <Empty title="Dê um destino ao seu dinheiro" description="Defina limites mensais por categoria." action={<Link className="button secondary" to="/app/ajustes/orcamentos">Criar orçamento</Link>} />}</section></div>
  <p className="balance-note">O saldo representa o que você registrou no BS Wallet; não é um saldo consultado no banco.</p>
  <Button variant="secondary" className="dashboard-more-button" aria-expanded={showDetails} onClick={() => setShowDetails(value => !value)}>{showDetails ? 'Ocultar detalhes' : 'Ver mais detalhes'}<ChevronDown size={17} className={showDetails ? 'rotated' : ''} /></Button>
  <div className={`dashboard-secondary ${showDetails ? 'is-expanded' : 'is-collapsed'}`}><section className="panel"><div className="panel-heading"><h2>Previsões do mês</h2></div><div className="forecast-totals"><span>Receitas previstas<strong>{money(totals.forecastIncome)}</strong></span><span>Despesas previstas<strong>{money(totals.forecastExpense)}</strong></span></div>{upcoming.map(t => <div className="simple-row" key={t.id}><span><strong>{t.name}</strong><small>{dateBR(financialDate(t))}</small></span><strong>{money(t.amount)}</strong></div>)}{!upcoming.length && <p className="muted panel-note">Sem contas pendentes ou previstas neste mês.</p>}</section><section className="panel"><div className="panel-heading"><h2>Maiores gastos</h2></div>{largestExpenses.map(t => <div className="simple-row" key={t.id}><span className="row-title"><CategoryIcon name={categoryById.get(t.categoryId)?.icon} />{t.name}</span><strong>{money(t.amount)}</strong></div>)}{!confirmed.length && <p className="muted panel-note">Nenhuma despesa confirmada.</p>}</section><section className="panel"><div className="panel-heading"><h2>Seus cartões</h2><Link to="/app/cartoes" className="text-button">Ver cartões</Link></div>{state.cards.filter(c => c.scope === scope).map(card => { const current = confirmed.filter(t => t.cardId === card.id).reduce((sum, t) => sum + t.amount, 0); const account = card.cardType === 'debit' ? state.accounts.find(item => item.id === card.accountId) : undefined; const detail = card.cardType === 'debit' ? `${account?.name ?? 'Conta indisponível'} · saldo ${money(account ? accountBalance(account.id, state.transactions, state.transfers, state.cards) : 0)}` : `${money(cardUsage(card, transactions, state.invoices).available)} de limite disponível`; return <div className="simple-row" key={card.id}><span><strong>{card.name}</strong><small>{detail}</small></span><strong>{money(current)}</strong></div>; })}{!state.cards.some(c => c.scope === scope) && <p className="muted panel-note">Cadastre um cartão para acompanhar faturas ou débitos.</p>}</section></div></div>;
}
