import { useState, type FormEvent } from 'react';
import { ArrowDownLeft, ArrowUpRight, ArrowLeftRight, Paperclip } from 'lucide-react';
import { walletService } from '../data/wallet-service';
import { addDays, invoiceCycle, moneyInput, parseMoney, today } from '../domain/finance';
import type { Entity, EntityMap, Frequency, Scope, Transaction } from '../domain/types';
import { useWallet } from './WalletContext';
import { Button, ErrorText, Field, Modal, frequencyLabels, statusLabels } from './ui';

const get = (form: FormData, key: string) => String(form.get(key) ?? '').trim();
const optional = (form: FormData, key: string) => get(form, key) || undefined;
type CatalogKind = 'accounts' | 'cards' | 'categories' | 'people' | 'budgets' | 'recurrences';
const titles: Record<CatalogKind, string> = { accounts: 'conta', cards: 'cartão', categories: 'categoria', people: 'pessoa', budgets: 'orçamento', recurrences: 'recorrência' };
function ScopeField({ value, change }: { value: Scope; change: (scope: Scope) => void }) {
  const { state } = useWallet();
  return <Field label="Carteira"><select name="scope" value={value} onChange={e => change(e.target.value as Scope)}><option value="personal">Pessoal • privada</option>{state.workspace.sharingEnabled && <option value="shared">Família • compartilhada</option>}</select></Field>;
}
export function CatalogEditor({ kind, existing, onClose }: { kind: CatalogKind; existing?: Entity; onClose: () => void }) {
  const { ctx, state, month, scope: currentScope, toast } = useWallet();
  const item = existing as (Partial<Omit<EntityMap['accounts'], 'type'> & EntityMap['cards'] & Omit<EntityMap['categories'], 'type'> & EntityMap['people'] & EntityMap['budgets'] & Omit<EntityMap['recurrences'], 'type'>> & { type?: string }) | undefined;
  const [scope, setScope] = useState<Scope>(existing?.scope ?? currentScope), [type, setType] = useState(item?.type === 'income' ? 'income' : 'expense');
  const [cardType, setCardType] = useState<'credit' | 'debit'>(item?.cardType ?? 'credit');
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [frequency, setFrequency] = useState<Frequency>(item?.frequency ?? 'monthly');
  const list = (kind: 'people' | 'accounts' | 'cards' | 'categories') => state[kind].filter(e => e.active && (kind === 'categories' || e.scope === scope || (scope === 'personal' && kind !== 'cards' && kind !== 'accounts' && e.scope === 'shared')));
  const select = (name: string, label: string, entries: { id: string; name: string }[], required = false) => <Field label={label}><select name={name} defaultValue={String(item?.[name as keyof typeof item] ?? '')} required={required}><option value="">{required ? 'Selecione' : 'Não informar'}</option>{entries.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></Field>;
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const f = new FormData(event.currentTarget);
    try {
      let input: Record<string, unknown> = { name: get(f, 'name'), scope, active: f.get('active') === 'on' };
      if (kind === 'accounts') input = { ...input, institution: get(f, 'institution'), type: get(f, 'accountType'), ownerPersonId: optional(f, 'ownerPersonId'), notes: get(f, 'notes') };
      if (kind === 'cards') input = { ...input, bank: get(f, 'bank'), brand: get(f, 'brand'), last4Digits: get(f, 'last4Digits'), cardType, totalLimit: cardType === 'credit' ? parseMoney(get(f, 'totalLimit')) : 0, closingDay: cardType === 'credit' ? Number(f.get('closingDay')) : 0, dueDay: cardType === 'credit' ? Number(f.get('dueDay')) : 0, ownerPersonId: get(f, 'ownerPersonId'), accountId: optional(f, 'accountId'), additionalOfCardId: cardType === 'credit' ? optional(f, 'additionalOfCardId') : undefined, notes: get(f, 'notes') };
      if (kind === 'categories') input = { ...input, icon: get(f, 'icon'), type: get(f, 'categoryType') };
      if (kind === 'people') input = { ...input, linkedUserId: optional(f, 'linkedUserId'), monthlySpendingLimitEnabled: f.get('monthlySpendingLimitEnabled') === 'on', monthlySpendingLimit: parseMoney(get(f, 'monthlySpendingLimit') || '0'), allowedCategoryIds: f.getAll('allowedCategoryIds').map(String) };
      if (kind === 'budgets') input = { ...input, month: get(f, 'month'), categoryId: get(f, 'categoryId'), personId: optional(f, 'personId'), limitAmount: parseMoney(get(f, 'limitAmount')), thresholds: [80, 90, 100] };
      if (kind === 'recurrences') input = { ...input, amount: parseMoney(get(f, 'amount')), type, categoryId: get(f, 'categoryId'), personId: optional(f, 'personId'), accountId: optional(f, 'accountId'), cardId: type === 'income' ? undefined : optional(f, 'cardId'), frequency, customIntervalValue: Number(f.get('customIntervalValue') || 1), customIntervalUnit: get(f, 'customIntervalUnit') || 'month', startDate: get(f, 'startDate'), endDate: optional(f, 'endDate'), nextOccurrenceDate: item?.nextOccurrenceDate || get(f, 'startDate'), autoConfirm: f.get('autoConfirm') === 'on', notes: get(f, 'notes') };
      await walletService.save(ctx, kind, input, existing?.id, existing?.version);
      if (kind === 'recurrences') await walletService.refresh(ctx);
      toast('Cadastro salvo no dispositivo.'); onClose();
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <Modal title={`${existing ? 'Editar' : 'Adicionar'} ${titles[kind]}`} onClose={onClose} wide preventViewportZoom={!existing}><form onSubmit={submit}><div className="form-grid"><Field label="Nome" wide><input autoFocus name="name" defaultValue={item?.name} required maxLength={160} placeholder={kind === 'cards' ? 'Ex.: Cartão Principal' : kind === 'people' ? 'Como essa pessoa se chama?' : 'Dê um nome fácil de reconhecer'} /></Field>{kind !== 'categories' && <ScopeField value={scope} change={setScope} />}<label className="check field-check"><input name="active" type="checkbox" defaultChecked={item?.active ?? true} />{kind === 'recurrences' ? 'Recorrência ativa' : 'Cadastro ativo'}</label>
    {kind === 'accounts' && <><Field label="Instituição"><input name="institution" defaultValue={item?.institution} /></Field><Field label="Tipo de conta"><select name="accountType" defaultValue={(existing as EntityMap['accounts'])?.type ?? 'checking'}><option value="checking">Conta corrente</option><option value="digital">Conta digital</option><option value="savings">Poupança</option><option value="cash">Dinheiro</option><option value="other">Outra</option></select></Field>{select('ownerPersonId', 'Titular', list('people'))}</>}
    {kind === 'cards' && <><Field label="Tipo do cartão"><select value={cardType} onChange={event => setCardType(event.target.value as 'credit' | 'debit')}><option value="credit">Crédito</option><option value="debit">Débito</option></select></Field><Field label="Banco"><input name="bank" required defaultValue={item?.bank} /></Field><Field label="Bandeira"><select name="brand" defaultValue={item?.brand ?? 'Mastercard'}>{['Mastercard', 'Visa', 'Elo', 'American Express', 'Outra'].map(v => <option key={v}>{v}</option>)}</select></Field><Field label="Últimos 4 dígitos"><input name="last4Digits" required inputMode="numeric" pattern="\d{4}" maxLength={4} defaultValue={item?.last4Digits} placeholder="1234" autoComplete="off" /></Field>{cardType === 'credit' && <><Field label="Limite total (R$)"><input name="totalLimit" required inputMode="decimal" defaultValue={item?.totalLimit ? moneyInput(item.totalLimit) : ''} placeholder="5.000,00" /></Field><Field label="Dia do fechamento"><input name="closingDay" type="number" min={1} max={31} required defaultValue={item?.closingDay || 10} /></Field><Field label="Dia do vencimento"><input name="dueDay" type="number" min={1} max={31} required defaultValue={item?.dueDay || 17} /></Field></>}{select('ownerPersonId', 'Titular', list('people'), true)}{select('accountId', cardType === 'debit' ? 'Conta debitada' : 'Conta vinculada', list('accounts'), cardType === 'debit')}{cardType === 'credit' && select('additionalOfCardId', 'Adicional de', list('cards').filter(c => c.id !== existing?.id && (c as EntityMap['cards']).cardType === 'credit'))}<p className="form-note wide">{cardType === 'debit' ? 'As compras neste cartão serão descontadas do saldo da conta vinculada.' : 'Guarde somente os quatro últimos dígitos. Nunca informe o número completo, CVV ou senha do cartão.'}</p></>}
    {kind === 'categories' && <><Field label="Tipo"><select name="categoryType" defaultValue={(existing as EntityMap['categories'])?.type ?? 'expense'}><option value="expense">Despesa</option><option value="income">Receita</option><option value="both">Ambos</option></select></Field><Field label="Ícone"><select name="icon" defaultValue={item?.icon ?? 'shopping'}>{Object.entries({ shopping: 'Carrinho', utensils: 'Restaurante', car: 'Carro', home: 'Casa', heart: 'Saúde', sparkles: 'Lazer', wallet: 'Carteira', briefcase: 'Trabalho', file: 'Documento' }).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><p className="form-note wide">A categoria ficará disponível nas carteiras pessoal e familiar.</p></>}
    {kind === 'people' && <>{select('linkedUserId', 'Conta de usuário (opcional)', state.members.filter(m => m.status === 'active').map(m => ({ id: m.userId, name: m.name })))}<Field label="Limite mensal (R$)"><input name="monthlySpendingLimit" inputMode="decimal" defaultValue={moneyInput(item?.monthlySpendingLimit ?? 0)} /></Field><label className="check wide"><input type="checkbox" name="monthlySpendingLimitEnabled" defaultChecked={item?.monthlySpendingLimitEnabled} />Ativar limite mensal de gastos</label><fieldset className="field wide category-field"><legend>Categorias permitidas</legend><div className="permission-list category-checklist">{list('categories').map(category => <label className="check" key={category.id}><input name="allowedCategoryIds" type="checkbox" value={category.id} defaultChecked={item?.allowedCategoryIds?.includes(category.id)} />{category.name}</label>)}</div><small>Nenhuma selecionada permite todas as categorias.</small></fieldset></>}
    {kind === 'budgets' && <><Field label="Mês"><input name="month" type="month" required defaultValue={item?.month ?? month} /></Field><Field label="Limite (R$)"><input name="limitAmount" required inputMode="decimal" defaultValue={item?.limitAmount ? moneyInput(item.limitAmount) : ''} /></Field>{select('categoryId', 'Categoria', list('categories').filter(c => (c as EntityMap['categories']).type !== 'income'), true)}{select('personId', 'Pessoa (opcional)', list('people'))}<p className="form-note wide">Alertas em 80%, 90% e 100%. Somente despesas confirmadas consomem o orçamento.</p></>}
    {kind === 'recurrences' && <><Field label="Tipo"><select name="type" value={type} onChange={e => setType(e.target.value)}><option value="expense">Despesa</option><option value="income">Receita</option></select></Field><Field label="Valor (R$)"><input name="amount" inputMode="decimal" required defaultValue={item?.amount ? moneyInput(item.amount) : ''} /></Field>{select('categoryId', 'Categoria', list('categories').filter(c => (c as EntityMap['categories']).type === type || (c as EntityMap['categories']).type === 'both'), true)}{select('personId', 'Pessoa', list('people'))}{select('accountId', 'Conta', list('accounts'))}{type === 'expense' && select('cardId', 'Cartão', list('cards'))}<Field label="Frequência"><select value={frequency} onChange={e => setFrequency(e.target.value as Frequency)}>{Object.entries(frequencyLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field>{frequency === 'custom' && <><Field label="Repetir a cada"><input type="number" name="customIntervalValue" min={1} max={365} defaultValue={item?.customIntervalValue ?? 1} required /></Field><Field label="Unidade"><select name="customIntervalUnit" defaultValue={item?.customIntervalUnit ?? 'month'}><option value="day">Dias</option><option value="week">Semanas</option><option value="month">Meses</option><option value="year">Anos</option></select></Field></>}<Field label="Data de início"><input type="date" name="startDate" defaultValue={item?.startDate ?? today()} required /></Field><Field label="Data de fim (opcional)"><input type="date" name="endDate" defaultValue={item?.endDate} /></Field><label className="check wide"><input name="autoConfirm" type="checkbox" defaultChecked={item?.autoConfirm ?? false} />Confirmar automaticamente na data prevista</label><p className="form-note wide">Sem confirmação automática, cada ocorrência começa como previsão. A geração acontece ao abrir o app e enquanto ele estiver em uso.</p></>}
    {['accounts', 'cards', 'recurrences'].includes(kind) && <Field label="Observações" wide><textarea name="notes" maxLength={2000} defaultValue={item?.notes} /></Field>}
  </div><ErrorText error={error} /><footer className="form-actions"><Button type="button" variant="secondary" onClick={onClose}>Cancelar</Button><Button disabled={busy} type="submit">{busy ? 'Salvando…' : 'Salvar'}</Button></footer></form></Modal>;
}
export function TransactionEditor({ existing, initialType = 'expense', initialCard, onClose }: { existing?: Transaction; initialType?: 'expense' | 'income' | 'transfer'; initialCard?: string; onClose: () => void }) {
  const { ctx, state, scope: currentScope, toast } = useWallet();
  const [type, setType] = useState(existing?.type ?? initialType), [mode, setMode] = useState(existing?.paymentMode ?? 'single');
  const [scope, setScope] = useState<Scope>(existing?.scope ?? currentScope), [cardId, setCardId] = useState(existing?.cardId ?? initialCard ?? '');
  const [date, setDate] = useState(existing?.transactionDate ?? today()), [series, setSeries] = useState(false);
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  const card = state.cards.find(c => c.id === cardId);
  const available = (kind: 'categories' | 'people' | 'cards' | 'accounts') => state[kind].filter(e => (e.active || existing && [existing.categoryId, existing.personId, existing.cardId, existing.accountId].includes(e.id)) && (e.scope === scope || scope === 'personal' && ['categories', 'people'].includes(kind)));
  const [invoiceMonth, setInvoiceMonth] = useState(existing?.invoiceId ? state.invoices.find(i => i.id === existing.invoiceId)?.cycleMonth ?? '' : '');
  function changeScope(scope: Scope) { setScope(scope); setCardId(''); }
  function calculatedCycle() { try { return card?.cardType === 'credit' ? invoiceCycle(date, card.closingDay, card.dueDay, invoiceMonth || undefined) : undefined; } catch { return undefined; } }
  const cycle = calculatedCycle();
  if (mode === 'recurring' && !existing) return <CatalogEditor kind="recurrences" onClose={onClose} />;
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const f = new FormData(event.currentTarget);
    try {
      if (type === 'transfer') { await walletService.save(ctx, 'transfers', { name: get(f, 'name'), amount: parseMoney(get(f, 'amount')), fromAccountId: get(f, 'fromAccountId'), toAccountId: get(f, 'toAccountId'), date, personId: optional(f, 'personId'), scope, notes: get(f, 'notes') }); }
      else {
        const data = { name: get(f, 'name'), amount: parseMoney(get(f, 'amount')), type, status: get(f, 'status') as Transaction['status'], transactionDate: date, competenceDate: existing?.competenceDate ?? date, categoryId: get(f, 'categoryId'), personId: optional(f, 'personId'), accountId: card?.cardType === 'debit' ? card.accountId : optional(f, 'accountId'), cardId: type === 'income' ? undefined : cardId || undefined, paymentMode: mode, scope, notes: get(f, 'notes') };
        let targetId = existing?.id;
        if (existing && series) await walletService.updateSeries(ctx, existing.id, { name: data.name, categoryId: data.categoryId, personId: data.personId, notes: data.notes });
        else if (existing) await walletService.save(ctx, 'transactions', data, existing.id, existing.version, invoiceMonth || undefined);
        else { const result = await walletService.createTransaction(ctx, data, Number(f.get('installments') || 1), invoiceMonth || undefined); targetId = result[0].id; }
        const files = f.getAll('attachments').filter((file): file is File => file instanceof File && file.size > 0);
        try { for (const file of files) await walletService.addAttachment(ctx, targetId!, file); } catch (e) { toast(`Lançamento salvo. Anexo não salvo: ${(e as Error).message} Abra o lançamento para tentar novamente.`); onClose(); return; }
      }
      await walletService.refresh(ctx); toast(type === 'transfer' ? 'Transferência registrada. Seus totais de receita e despesa permanecem iguais.' : 'Lançamento salvo no dispositivo.'); onClose();
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <Modal title={existing ? 'Editar lançamento' : 'Adicionar lançamento'} onClose={onClose} wide preventViewportZoom={!existing}><form onSubmit={submit}>
    {!existing && <div className="type-tabs">{([['expense', 'Despesa', ArrowDownLeft], ['income', 'Receita', ArrowUpRight], ['transfer', 'Transferência', ArrowLeftRight]] as const).map(([value, label, Icon]) => <button key={value} type="button" aria-pressed={type === value} className={type === value ? 'selected' : ''} onClick={() => { setType(value); if (value === 'income') setCardId(''); }}><Icon size={17} />{label}</button>)}</div>}
    {existing?.installmentGroupId && <label className="check series-choice"><input type="checkbox" checked={series} onChange={e => setSeries(e.target.checked)} />Editar nome, categoria, pessoa e observações de toda a série</label>}
    <div className="form-grid"><Field label="Descrição" wide><input name="name" autoFocus required maxLength={160} defaultValue={existing?.name} placeholder={type === 'transfer' ? 'Ex.: Reserva na conta digital' : 'Ex.: Mercado da semana'} /></Field><Field label={mode === 'installment' && !existing ? 'Valor total da compra (R$)' : 'Valor (R$)'}><input name="amount" inputMode="decimal" required readOnly={series} defaultValue={existing ? moneyInput(existing.amount) : ''} placeholder="0,00" /></Field><Field label="Data"><input name="date" type="date" required value={date} readOnly={series} onChange={e => setDate(e.target.value)} /></Field><ScopeField value={scope} change={changeScope} />
    {type !== 'transfer' && <><Field label="Forma"><select value={mode} disabled={Boolean(existing)} onChange={e => setMode(e.target.value as Transaction['paymentMode'])}><option value="single">Única</option>{type === 'expense' && card?.cardType !== 'debit' && <option value="installment">Parcelada</option>}<option value="recurring">Recorrente</option></select></Field><Field label="Categoria"><select name="categoryId" defaultValue={existing?.categoryId ?? ''} required><option value="">Selecione a categoria</option>{available('categories').filter(c => (c as EntityMap['categories']).type === type || (c as EntityMap['categories']).type === 'both').map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Status"><select name="status" defaultValue={existing?.status ?? 'confirmed'}>{Object.entries(statusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field></>}
    <Field label="Pessoa (opcional)"><select name="personId" defaultValue={existing?.personId ?? ''}><option value="">Não informar</option>{available('people').map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>
    {type === 'transfer' ? <>{['fromAccountId', 'toAccountId'].map((key, i) => <Field key={key} label={i === 0 ? 'Conta de origem' : 'Conta de destino'}><select name={key} required><option value="">Selecione a conta</option>{available('accounts').map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></Field>)}<p className="form-note wide">Transferências movimentam valores entre contas e não são receita nem despesa.</p></> : <>{card?.cardType === 'debit' ? <Field label="Conta debitada"><input readOnly value={state.accounts.find(account => account.id === card.accountId)?.name ?? 'Conta vinculada indisponível'} /></Field> : <Field label="Conta (opcional)"><select name="accountId" defaultValue={existing?.accountId ?? ''}><option value="">Não informar</option>{available('accounts').map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></Field>}{type === 'expense' && <Field label={mode === 'installment' ? 'Cartão' : 'Cartão (opcional)'}><select value={cardId} onChange={e => { const next = state.cards.find(card => card.id === e.target.value); setCardId(e.target.value); setInvoiceMonth(''); if (next?.cardType === 'debit') setMode('single'); }} required={mode === 'installment'}><option value="">Sem cartão</option>{available('cards').map(c => <option key={c.id} value={c.id}>{c.name} · {(c as EntityMap['cards']).cardType === 'debit' ? 'Débito' : 'Crédito'}</option>)}</select></Field>}{mode === 'installment' && !existing && <Field label="Quantidade de parcelas"><input name="installments" type="number" min={2} max={360} defaultValue={2} required /></Field>}{card?.cardType === 'credit' && <Field label="Mês de fechamento da primeira fatura" hint={cycle ? `Fechamento: ${cycle.closingDate.split('-').reverse().join('/')} · Vencimento: ${cycle.dueDate.split('-').reverse().join('/')}` : undefined}><input type="month" value={invoiceMonth || cycle?.cycleMonth || ''} onChange={e => setInvoiceMonth(e.target.value)} /></Field>}</>}
    <Field label="Observações" wide><textarea name="notes" maxLength={2000} rows={2} defaultValue={existing?.notes} placeholder="Algum detalhe que você queira lembrar?" /></Field>
    {type !== 'transfer' && !series && <Field label="Comprovantes" hint={`JPEG, PNG, WebP ou PDF. Até ${state.preferences.attachmentMaxMB} MB por arquivo. Em parcelas, anexados à primeira parcela.`} wide><div className="file-input"><Paperclip size={18} /><input type="file" name="attachments" accept="image/jpeg,image/png,image/webp,application/pdf" multiple /></div></Field>}
    </div><ErrorText error={error} /><footer className="form-actions"><Button variant="secondary" type="button" onClick={onClose}>Cancelar</Button><Button disabled={busy} type="submit">{busy ? 'Salvando…' : series ? 'Salvar em toda a série' : existing ? 'Salvar alterações' : 'Adicionar lançamento'}</Button></footer></form></Modal>;
}
