import { useEffect, useState } from 'react';
import { Check, Download, FileText, Pencil, Trash2, Upload } from 'lucide-react';
import { dateBR, financialDate, money } from '../domain/finance';
import { walletService } from '../data/wallet-service';
import type { Attachment, Transaction, Transfer } from '../domain/types';
import { useWallet } from './WalletContext';
import { Button, CategoryIcon, Empty, Modal, StatusBadge } from './ui';
import { TransactionEditor } from './Editors';
export type HistoryItem = (Transaction & { rowType: 'transaction' }) | (Transfer & { rowType: 'transfer' });
export function TransactionList({ items, compact = false }: { items: HistoryItem[]; compact?: boolean }) {
  const { state, run, ctx } = useWallet(); const [selected, setSelected] = useState<HistoryItem | null>(null);
  if (!items.length) return <Empty title="Nenhum lançamento por aqui" description="Adicione um lançamento ou ajuste os filtros para encontrar seus registros." />;
  return <><div className="table-scroll"><table className={`transaction-table ${compact ? 'compact' : ''}`}><thead><tr><th>Descrição</th><th className="hide-mobile">Categoria</th><th>Data</th><th className="hide-mobile">Status</th><th className="number">Valor</th></tr></thead><tbody>{items.map(item => {
    const transaction = item.rowType === 'transaction' ? item : null;
    const category = state.categories.find(c => c.id === transaction?.categoryId);
    return <tr key={item.id}><td><button className="transaction-name" onClick={() => setSelected(item)}><span className={`category-icon ${transaction?.type === 'income' ? 'income' : ''}`}><CategoryIcon name={item.rowType === 'transfer' ? 'transfer' : category?.icon} /></span><span>{item.name}{transaction?.installmentNumber && <small>Parcela {transaction.installmentNumber}/{transaction.installmentTotal}</small>}{!compact && <small>{state.people.find(p => p.id === transaction?.personId)?.name ?? (item.scope === 'personal' ? 'Carteira pessoal' : 'Carteira da família')}</small>}</span></button></td><td className="hide-mobile muted">{category?.name ?? 'Transferência'}</td><td className="date-cell">{dateBR(transaction ? financialDate(transaction) : (item as Transfer).date).slice(0, 5)}<small>{dateBR(transaction ? financialDate(transaction) : (item as Transfer).date).slice(6)}</small></td><td className="hide-mobile"><StatusBadge status={transaction?.status ?? 'Transferência'} /></td><td className={`number amount ${transaction?.type === 'income' ? 'income-text' : ''}`}>{transaction ? transaction.type === 'income' ? '+ ' : '− ' : '↔ '}{money(item.amount)}</td></tr>;
  })}</tbody></table></div>{selected?.rowType === 'transaction' && <TransactionDetail transaction={state.transactions.find(t => t.id === selected.id) ?? selected} onClose={() => setSelected(null)} />}{selected?.rowType === 'transfer' && <Modal title="Transferência" onClose={() => setSelected(null)}><div className="detail-amount">{money(selected.amount)}</div><p>{selected.name}</p><dl className="detail-grid"><dt>Origem</dt><dd>{state.accounts.find(a => a.id === selected.fromAccountId)?.name}</dd><dt>Destino</dt><dd>{state.accounts.find(a => a.id === selected.toAccountId)?.name}</dd><dt>Data</dt><dd>{dateBR(selected.date)}</dd></dl><p className="form-note">Não compõe receitas ou despesas.</p><Button variant="danger" onClick={async () => { if (window.confirm('Mover esta transferência para a lixeira por 30 dias?') && await run(() => walletService.remove(ctx, 'transfers', selected.id), 'Transferência movida para a lixeira.')) setSelected(null); }}><Trash2 size={17} />Excluir transferência</Button></Modal>}</>;
}
export function TransactionDetail({ transaction, onClose }: { transaction: Transaction; onClose: () => void }) {
  const { ctx, state, run, toast } = useWallet(); const [editing, setEditing] = useState(false), [files, setFiles] = useState<Attachment[]>([]), [fileError, setFileError] = useState('');
  const [deleteOpen, setDeleteOpen] = useState(false), [series, setSeries] = useState(false), [preview, setPreview] = useState<{ url: string; mime: string; name: string }>();
  const reloadFiles = () => walletService.attachments(ctx, transaction.id).then(setFiles).catch(e => setFileError(e.message));
  useEffect(() => { void reloadFiles(); }, [ctx, transaction.id]);
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview.url); }, [preview]);
  if (editing) return <TransactionEditor existing={transaction} onClose={onClose} />;
  const audit = state.audit.filter(a => a.entityId === transaction.id).slice().reverse();
  async function download(file: Attachment) { const url = URL.createObjectURL(file.blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = file.fileName; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  return <Modal title="Detalhes do lançamento" onClose={onClose} wide><div className="detail-heading"><div><p className="muted">{transaction.name}</p><div className="detail-amount">{money(transaction.amount)}</div></div><StatusBadge status={transaction.status} /></div><dl className="detail-grid"><dt>Categoria</dt><dd>{state.categories.find(c => c.id === transaction.categoryId)?.name}</dd><dt>Data da compra</dt><dd>{dateBR(transaction.transactionDate)}</dd><dt>Competência</dt><dd>{dateBR(transaction.competenceDate)}</dd><dt>Carteira</dt><dd>{transaction.scope === 'personal' ? 'Pessoal • privada' : 'Família • compartilhada'}</dd>{transaction.personId && <><dt>Pessoa</dt><dd>{state.people.find(p => p.id === transaction.personId)?.name}</dd></>}{transaction.cardId && <><dt>Cartão</dt><dd>{state.cards.find(c => c.id === transaction.cardId)?.name}</dd></>}{transaction.accountId && <><dt>Conta</dt><dd>{state.accounts.find(c => c.id === transaction.accountId)?.name}</dd></>}{transaction.installmentGroupId && <><dt>Parcela</dt><dd>{transaction.installmentNumber}/{transaction.installmentTotal}</dd></>}</dl>{transaction.notes && <p className="notes">{transaction.notes}</p>}
    <div className="detail-actions">{transaction.status !== 'confirmed' && transaction.status !== 'cancelled' && <Button onClick={async () => { if (await run(() => walletService.save(ctx, 'transactions', { ...transaction, status: 'confirmed' }, transaction.id, transaction.version), 'Lançamento confirmado.')) onClose(); }}><Check size={17} />Confirmar</Button>}<Button variant="secondary" onClick={() => setEditing(true)}><Pencil size={16} />Editar</Button><Button variant="ghost" onClick={() => setDeleteOpen(true)}><Trash2 size={16} />Excluir</Button></div>
    {deleteOpen && <div className="confirm-panel"><h3>Mover para a lixeira?</h3><p>Você poderá restaurar por 30 dias.</p>{(transaction.installmentGroupId || transaction.recurrenceId) && <label className="check"><input type="checkbox" checked={series} onChange={e => setSeries(e.target.checked)} />Excluir toda a série e suas ocorrências</label>}<div className="detail-actions"><Button variant="secondary" onClick={() => setDeleteOpen(false)}>Cancelar</Button><Button variant="danger" onClick={async () => { if (await run(() => walletService.remove(ctx, 'transactions', transaction.id, series), 'Movido para a lixeira.')) onClose(); }}>Confirmar exclusão</Button></div></div>}
    <section className="detail-section"><h3>Comprovantes</h3>{fileError && <p className="muted">{fileError}</p>}{files.map(file => <div className="attachment-row" key={file.id}><FileText size={20} /><button className="text-button" onClick={() => { if (!file.blob?.size) { toast('O arquivo não está disponível neste dispositivo.'); return; } setPreview({ url: URL.createObjectURL(file.blob), mime: file.mimeType, name: file.fileName }); }}>{file.fileName}</button><small>{(file.size / 1024).toFixed(1)} KB</small><button className="icon-button" aria-label={`Baixar ${file.fileName}`} onClick={() => download(file)}><Download size={17} /></button><button className="icon-button" aria-label={`Remover ${file.fileName}`} onClick={async () => { if (window.confirm('Remover este anexo definitivamente?') && await run(() => walletService.removeAttachment(ctx, file.id), 'Anexo removido.')) void reloadFiles(); }}><Trash2 size={17} /></button></div>)}{!files.length && !fileError && <p className="muted">Nenhum comprovante anexado.</p>}<label className="button secondary upload-label"><Upload size={17} />Anexar comprovante<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" multiple onChange={async e => { const selected = Array.from(e.target.files ?? []); for (const file of selected) await run(() => walletService.addAttachment(ctx, transaction.id, file), 'Comprovante salvo offline.'); void reloadFiles(); e.target.value = ''; }} /></label>{preview && <div className="attachment-preview"><div><span>{preview.name}</span><button className="text-button" onClick={() => setPreview(undefined)}>Fechar prévia</button></div>{preview.mime.startsWith('image/') ? <img src={preview.url} alt={preview.name} /> : <iframe title={preview.name} src={preview.url} sandbox="" />}</div>}</section>
    <section className="detail-section"><h3>Histórico de alterações</h3><ol className="audit-list">{audit.map(log => { const before = log.beforeData as Transaction | undefined, after = log.afterData as Transaction | undefined; return <li key={log.id}><span className="audit-dot" /><div><strong>{({ create: 'Lançamento criado', update: 'Lançamento alterado', delete: 'Movido para a lixeira', restore: 'Lançamento restaurado', status_change: 'Status alterado' } as Record<string, string>)[log.action] ?? log.action}</strong>{before?.amount && after?.amount !== before.amount && <p>Valor: {money(before.amount)} → {money(after?.amount ?? 0)}</p>}<small>{log.actorName} · {new Date(log.timestamp).toLocaleString('pt-BR')}</small></div></li>; })}</ol></section></Modal>;
}
